CREATE TABLE IF NOT EXISTS faculty (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,
    color VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS student (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    age INTEGER NOT NULL,
    gender VARCHAR(1) NOT NULL,
    faculty_id BIGINT REFERENCES faculty(id)
);

CREATE TABLE IF NOT EXISTS avatar (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    file_path TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    media_type VARCHAR(255) NOT NULL,
    data BLOB,
    student_id BIGINT UNIQUE REFERENCES student(id) ON DELETE CASCADE
);